# Generated by Django 5.1.1 on 2024-09-19 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('source_url', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='agent.optioncategory')),
            ],
            options={
                'unique_together': {('category', 'value')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('source_url', models.URLField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collections', models.ManyToManyField(related_name='products', to='agent.collection')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agent.product')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('options', models.ManyToManyField(related_name='variants', to='agent.optionvalue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='agent.product')),
            ],
        ),
        migrations.CreateModel(
            name='WixProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle_id', models.CharField(max_length=50, unique=True)),
                ('field_type', models.CharField(default='Product', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('product_image_url', models.TextField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('ribbon', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('surcharge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('discount_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inventory', models.CharField(default='InStock', max_length=50)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_option_name_1', models.CharField(blank=True, max_length=255, null=True)),
                ('product_option_type_1', models.CharField(blank=True, max_length=50, null=True)),
                ('product_option_description_1', models.TextField(blank=True, null=True)),
                ('product_option_name_2', models.CharField(blank=True, max_length=255, null=True)),
                ('product_option_type_2', models.CharField(blank=True, max_length=50, null=True)),
                ('product_option_description_2', models.TextField(blank=True, null=True)),
                ('product_option_name_3', models.CharField(blank=True, max_length=255, null=True)),
                ('product_option_type_3', models.CharField(blank=True, max_length=50, null=True)),
                ('product_option_description_3', models.TextField(blank=True, null=True)),
                ('product_option_name_4', models.CharField(blank=True, max_length=255, null=True)),
                ('product_option_type_4', models.CharField(blank=True, max_length=50, null=True)),
                ('product_option_description_4', models.TextField(blank=True, null=True)),
                ('product_option_name_5', models.CharField(blank=True, max_length=255, null=True)),
                ('product_option_type_5', models.CharField(blank=True, max_length=50, null=True)),
                ('product_option_description_5', models.TextField(blank=True, null=True)),
                ('product_option_name_6', models.CharField(blank=True, max_length=255, null=True)),
                ('product_option_type_6', models.CharField(blank=True, max_length=50, null=True)),
                ('product_option_description_6', models.TextField(blank=True, null=True)),
                ('additional_info_title_1', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_info_description_1', models.TextField(blank=True, null=True)),
                ('additional_info_title_2', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_info_description_2', models.TextField(blank=True, null=True)),
                ('additional_info_title_3', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_info_description_3', models.TextField(blank=True, null=True)),
                ('additional_info_title_4', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_info_description_4', models.TextField(blank=True, null=True)),
                ('additional_info_title_5', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_info_description_5', models.TextField(blank=True, null=True)),
                ('additional_info_title_6', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_info_description_6', models.TextField(blank=True, null=True)),
                ('custom_text_field_1', models.TextField(blank=True, null=True)),
                ('custom_text_char_limit_1', models.IntegerField(blank=True, null=True)),
                ('custom_text_mandatory_1', models.BooleanField(default=False)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wix_products', to='agent.collection')),
            ],
        ),
    ]
