# Generated by Django 5.1.1 on 2024-09-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wixproduct',
            name='handle_id',
            field=models.CharField(max_length=50),
        ),
    ]
