# Generated by Django 5.1.1 on 2024-09-19 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WixProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle_id', models.CharField(max_length=50, unique=True)),
                ('field_type', models.CharField(default='Product', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('product_image_url', models.TextField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=50, null=True)),
                ('ribbon', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('surcharge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('additional_info_title_1', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_info_description_1', models.TextField(blank=True, null=True)),
                ('additional_info_title_2', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_info_description_2', models.TextField(blank=True, null=True)),
                ('additional_info_title_3', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_info_description_3', models.TextField(blank=True, null=True)),
                ('additional_info_title_4', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_info_description_4', models.TextField(blank=True, null=True)),
                ('additional_info_title_5', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_info_description_5', models.TextField(blank=True, null=True)),
                ('additional_info_title_6', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_info_description_6', models.TextField(blank=True, null=True)),
                ('custom_text_field_1', models.TextField(blank=True, null=True)),
                ('custom_text_char_limit_1', models.IntegerField(blank=True, null=True)),
                ('custom_text_mandatory_1', models.BooleanField(default=False)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wix_products', to='agent.collection')),
            ],
        ),
    ]
