# Generated by Django 5.1.1 on 2024-09-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_alter_wixproduct_handle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_update',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
