# Generated by Django 5.1.1 on 2024-09-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_product_allow_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wixproduct',
            name='collection',
        ),
        migrations.AddField(
            model_name='wixproduct',
            name='collections',
            field=models.ManyToManyField(related_name='wix_products', to='agent.collection'),
        ),
    ]
