# Generated by Django 5.1.1 on 2024-09-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_alter_collection_title_alter_image_alt_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='source_url',
            field=models.URLField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='product',
            name='source_url',
            field=models.URLField(max_length=1024, unique=True),
        ),
    ]
