# Generated by Django 5.1.1 on 2024-09-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_alter_optioncategory_name_alter_optionvalue_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='csv_export',
            field=models.FileField(blank=True, null=True, upload_to='csv_exports/'),
        ),
    ]
